### ISSUE TITLE
Guest_Packets_Count not working

### ISSUE THREAD

**Issue by J3n50m4t** [pdreker/fritzbox_exporter#34]
I'm using the provisioned Grafana Dashboard and played around with 2 Devices in my Guest wifi. 

The image shows a speedtest on a wifi device in my guest network. The packets count doesn't show anything. 

Packets for all others Wifis and LAN do work though. 

<img width="1440" alt="Bildschirmfoto 2021-03-16 um 22 00 52" src="https://user-images.githubusercontent.com/13681191/111379164-15e43280-86a3-11eb-924a-231e847dcde6.png">

## Prometheus Output:

```

fritz_wifi_guest_packets_count_total{direction="rx", enabled="1", instance="fritz:9787", job="fritz", serial="removed", ssid="FRITZ! Hotspot", standard="n"}
fritz_uptime_seconds_total{modelname="FRITZ!Box 7590",serial="removed",softwareversion="154.07.21"} 2.716208e+06


```

## docker-compose service
```
  fritz:
    privileged: true
    image: pdreker/fritz_exporter
    expose:
      - 9787
    ports:
      - 9787:9787
    environment:
      - "FRITZ_EXPORTER_CONFIG=192.168.178.1,username,password"
    restart: always
    networks:
      - back-tier
```
